version: "3.8"
services:
  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    volumes:
      - ../backend:/app
  frontend:
    build: ../frontend
    command: npm run dev
    ports: ["5173:5173"]
    volumes:
      - ../frontend:/app
